import { existsSync, readFileSync, writeFileSync } from 'node:fs';

import { createDeviceMasterKeyCreationLock } from '../../src/device-master-key-creation-lock.ts';
import { loadDeviceMasterKey, type DeviceMasterKeyCredential } from '../../src/device-master-key.ts';

const [mode, databasePath, credentialPath, generatedByteText, lockDatabasePath] = process.argv.slice(2);
if (mode === undefined || databasePath === undefined || credentialPath === undefined || generatedByteText === undefined || lockDatabasePath === undefined) {
  throw new Error('Usage: device-master-key-lock-child <mode> <database> <credential> <generated-byte> <credential-lock-database>');
}
const generatedByte = Number(generatedByteText);
if (!Number.isInteger(generatedByte) || generatedByte < 0 || generatedByte > 255) {
  throw new Error(`Invalid generated byte: ${generatedByteText}`);
}

const waitForInput = async (): Promise<void> => await new Promise(resolve => {
  process.stdin.once('data', () => resolve());
});
const waitForReleaseMarker = async (): Promise<void> => {
  const releasePath = `${credentialPath}.release-${generatedByte}`;
  while (!existsSync(releasePath)) {
    await new Promise(resolve => setTimeout(resolve, 10));
  }
};

process.env.FLOWAY_DB_PATH = databasePath;
const creationLock = createDeviceMasterKeyCreationLock({ lockDatabasePath });
if (mode === 'same-process') {
  const secondLock = createDeviceMasterKeyCreationLock({ lockDatabasePath });
  let release!: () => void;
  const released = new Promise<void>(resolveRelease => { release = resolveRelease; });
  let firstEntered!: () => void;
  const entered = new Promise<void>(resolveEntered => { firstEntered = resolveEntered; });
  const first = creationLock.run(async () => {
    firstEntered();
    await released;
  });
  await entered;
  setImmediate(release);
  await Promise.all([first, secondLock.run(async () => undefined)]);
  process.stdout.write('SAME_PROCESS_SERIALIZED\n');
  process.exit(0);
}
if (mode === 'hold') {
  await creationLock.run(async () => {
    process.stdout.write('LOCKED\n');
    await waitForInput();
  });
  process.exit(0);
}

const credential: DeviceMasterKeyCredential = {
  getSecret: () => existsSync(credentialPath) ? readFileSync(credentialPath) : null,
  setSecret: async secret => {
    writeFileSync(credentialPath, secret, { mode: 0o600 });
    if (mode === 'pause-after-write') {
      process.stdout.write('PERSISTED\n');
      await waitForReleaseMarker();
    }
  },
};
process.stdout.write('ATTEMPTING\n');
const key = await loadDeviceMasterKey(
  creationLock,
  true,
  credential,
  () => new Uint8Array(32).fill(generatedByte),
);
process.stdout.write(`KEY ${Buffer.from(key).toString('hex')}\n`);
