import { existsSync, readFileSync, writeFileSync } from 'node:fs';

import { createDeviceMasterKeyCreationLock } from '../../src/device-master-key-creation-lock.ts';
import { loadDeviceMasterKey, type DeviceMasterKeyCredential } from '../../src/device-master-key.ts';

const [mode, databasePath, credentialPath, generatedByteText] = process.argv.slice(2);
if (mode === undefined || databasePath === undefined || credentialPath === undefined || generatedByteText === undefined) {
  throw new Error('Usage: device-master-key-lock-child <mode> <database> <credential> <generated-byte>');
}
const generatedByte = Number(generatedByteText);
if (!Number.isInteger(generatedByte) || generatedByte < 0 || generatedByte > 255) {
  throw new Error(`Invalid generated byte: ${generatedByteText}`);
}

const waitForInput = async (): Promise<void> => await new Promise(resolve => {
  process.stdin.once('data', () => resolve());
});
const waitForReleaseMarker = async (): Promise<void> => {
  const releasePath = `${credentialPath}.release-${generatedByte}`;
  while (!existsSync(releasePath)) {
    await new Promise(resolve => setTimeout(resolve, 10));
  }
};

const creationLock = createDeviceMasterKeyCreationLock(databasePath);
if (mode === 'hold') {
  await creationLock.run(async () => {
    process.stdout.write('LOCKED\n');
    await waitForInput();
  });
  process.exit(0);
}

const credential: DeviceMasterKeyCredential = {
  getSecret: () => existsSync(credentialPath) ? readFileSync(credentialPath) : null,
  setSecret: async secret => {
    writeFileSync(credentialPath, secret, { mode: 0o600 });
    if (mode === 'pause-after-write') {
      process.stdout.write('PERSISTED\n');
      await waitForReleaseMarker();
    }
  },
};
const key = await loadDeviceMasterKey(
  creationLock,
  true,
  credential,
  () => new Uint8Array(32).fill(generatedByte),
);
process.stdout.write(`KEY ${Buffer.from(key).toString('hex')}\n`);
